// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/chat/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/chat/[id].get').default>>>>
    }
    '/chatslist': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/chatslist.get').default>>>>
    }
    '/message': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/message.post').default>>>>
    }
  }
}
export {}